### ISSUE TITLE
The window not appear

### ISSUE THREAD

**Issue by ipol2n** [Siutsch/AIO---All-in-one-tweaks#19]
Hi,

I plugged the usb in and then started the car, but nothing appeared.
I waited for an half hour but nothing happen.

My firmware version is 56.00.240 4A N.

Do you have any suggestion?

I am happy to help you test the new script that can fix this issue.

**Comment by Trevelopment** [comment]
Have you tried reformatting your USB drive (as FAT32) before copying tweak files?   That has fixed this issue for me in the past.

**Comment by ipol2n** [comment]
Yes, I formatted my USB to FAT32 before copying the files.

**Comment by ipol2n** [comment]
I tried to format and copy files again. It works now. 
Thank you.
