### ISSUE TITLE
Doesn't seem to work in this rev

### ISSUE THREAD

**Issue by middleagedman** [Siutsch/AIO---All-in-one-tweaks#6]
I've used this before, so I believe I should be expecting menu choices.  When I run it, it detects my country code, shows the screen with your FAQ, but then all I see is this:

http://imgur.com/a/PNqep

If I choose "0", I get this next, and then it loops back to the first screenshot

http://imgur.com/a/gIrlN

**Comment by middleagedman** [comment]
Well nm maybe.. I pulled down the ZIP from your post instead of cloning from here.. not sure why there is a difference.

**Comment by Siutsch** [comment]
Hmm.
If it works with download from google drive, then I have to test that.
Both versions should be the same ...  :(

**Comment by zholmes1** [comment]
Drive version worked, ZIP from GitHub gave me the exact same issue. Great work though!

**Comment by Siutsch** [comment]
Added .gitattributes to prevent git from changing choose.cmd to unix.
