### ISSUE TITLE
Fix for WiFi enable

### ISSUE THREAD

**Issue by middleagedman** [Siutsch/AIO---All-in-one-tweaks#9]
I believe this line is wrong in the tweaks.sh file that gets generated.  The -l doesn't mean "line", but rather "line length", so the sed replaces ALL && with || in the file.  I believe the correct syntax is as follows:

```
169c169
< 		sed -i -l $LN 's/&&/||/' /jci/gui/apps/syssettings/js/syssettingsApp.js
---
>               sed -i "${LN}s/&&/||/' /jci/gui/apps/syssettings/js/syssettingsApp.js

```

**Comment by middleagedman** [comment]
Just tested this and it worked.. I now see the WiFi menu option in my devices (2016 Mazda 6 NA)

**Comment by Siutsch** [comment]
Thanks! :)

Changed that.

**Comment by Siutsch** [comment]
Are you sure, that it is:

"${LN}s/&&/||/'

" at the beginning and ' at the end?

Or it's this?

'${LN}s/&&/||/'

**Comment by middleagedman** [comment]
Oh good catch!  It's double quotes.. " and "

**Comment by Siutsch** [comment]
Thanks. Corrected that.

**Comment by frozen-solid** [comment]
I'm still not seeing wifi options on my car even after applying this fix.
